image: node:20  # Usa Node.js 18

stages:
  - deploy

deploy_production:
  stage: deploy
  before_script:
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H "$SSH_HOST" >> ~/.ssh/known_hosts  # Evita prompt ao conectar
  script:
    - ssh $SSH_USER@$SSH_HOST "npm i -g pm2 && cd $PROJECT_PATH && git pull origin main && yarn && yarn bd && pm2 restart all"
  only:
    - main  # Apenas quando um push for feito na branch `main`