-- AlterTable
ALTER TABLE "User" ADD COLUMN     "parceirosTreepy" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "florestas" ADD COLUMN     "dataFim" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "dataInicio" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "projetoAtivo" BOOLEAN NOT NULL DEFAULT true;
